@append "https://cdn.firebase.com/js/client/2.0.2/firebase.js";

@append "lib/firepad.js";
@append "lib/meeting.js";
@append "lib/addon.js";

Script "run.js" {
    @append {
        dayside.plugins.collaborate();
        dayside({
            root: teacss.path.absolute("./../../../"),
            ajax_url: teacss.path.absolute("./demo.php")
        });
    }
}